In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [3]:
import pandas as pd

In [4]:
excel_file = 'for testing.xls'

In [7]:

df = pd.read_excel (r'C:\Users\Puneet Kumar\Desktop\testing.xlsx')

In [8]:
df

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9
0,51415,10th foundation $ 10th ntse $ mathematics $ al...,lm193876,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",equations reducible to the linear form
1,51416,10th foundation $ 10th ntse $ mathematics $ al...,lm193875,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",reducing equations to simpler form
2,51417,10th foundation $ 10th ntse $ mathematics $ al...,lm193873,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some more applications
3,51418,10th foundation $ 10th ntse $ mathematics $ al...,lm193871,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations having the variable on both...
4,51419,10th foundation $ 10th ntse $ mathematics $ al...,lm193869,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some applications
5,51420,10th foundation $ 10th ntse $ mathematics $ al...,lm193867,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations which have linear expressio...
6,51421,10th foundation $ 10th ntse $ mathematics $ al...,lm193865,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",introduction linear equations in one variable
7,74553,dummy goal $ foundation 10 ntse $ scholastic a...,lm218868,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,greece
8,74554,dummy goal $ foundation 10 ntse $ scholastic a...,lm218867,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,italy and germany
9,74555,dummy goal $ foundation 10 ntse $ scholastic a...,lm218866,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,hungray
10,74556,dummy goal $ foundation 10 ntse $ scholastic a...,lm218865,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,general characteristics of the movements in p...
11,74557,dummy goal $ foundation 10 ntse $ scholastic a...,lm218864,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the ideas of gluseppe mazzini etc
12,74558,dummy goal $ foundation 10 ntse $ scholastic a...,lm218863,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the growth of nationalism in europe after the...
13,95325,lectureship $ ugc net paper 2 $ urdu $ تاریخ ز...,lm522197,lectureship,ugc net paper 2,urdu,تاریخ زبان اردو,، پراکرت و اپ بھرنش,، پراکرت و اپ بھرنش
14,93516,lectureship $ ugc net paper 2 $ chinese $ 现代汉语...,lm541533,lectureship,ugc net paper 2,chinese,现代汉语语法,‘把’,句法
15,95589,lectureship $ ugc net paper 2 $ arab culture a...,lm402639,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1757: british colonialism and its expansion,1757: british colonialism and its expansion
16,95588,lectureship $ ugc net paper 2 $ arab culture a...,lm402640,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1857: first war of independence and its conse...,1857: first war of independence and its conse...
17,135962,andhra pradesh board $ 6th andhra pradesh boar...,lm483641,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,understanding of 3d shapes
18,135963,andhra pradesh board $ 6th andhra pradesh boar...,lm483640,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,symmetry
19,135964,andhra pradesh board $ 6th andhra pradesh boar...,lm483639,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of circle
20,135965,andhra pradesh board $ 6th andhra pradesh boar...,lm483638,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of quadrilateral
21,135966,andhra pradesh board $ 6th andhra pradesh boar...,lm483637,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,polygons
22,135967,andhra pradesh board $ 6th andhra pradesh boar...,lm483636,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of triangle
23,177313,engineering $ jee advanced $ mathematics $ vec...,lm205920,engineering,jee advanced,mathematics,vector algebra,3d geometry,geometrical applications
24,177314,engineering $ jee advanced $ mathematics $ vec...,lm205918,engineering,jee advanced,mathematics,vector algebra,3d geometry,planes and geometry
25,177315,engineering $ jee advanced $ mathematics $ vec...,lm205916,engineering,jee advanced,mathematics,vector algebra,3d geometry,straight lines
26,177316,engineering $ jee advanced $ mathematics $ vec...,lm205913,engineering,jee advanced,mathematics,vector algebra,3d geometry,points and plane
27,177317,engineering $ jee advanced $ mathematics $ vec...,lm205911,engineering,jee advanced,mathematics,vector algebra,3d geometry,line and plane
28,177318,engineering $ jee advanced $ mathematics $ vec...,lm205909,engineering,jee advanced,mathematics,vector algebra,3d geometry,equation of line in different forms
29,177319,engineering $ jee advanced $ mathematics $ vec...,lm205907,engineering,jee advanced,mathematics,vector algebra,3d geometry,plane
30,177320,engineering $ jee advanced $ mathematics $ vec...,lm205905,engineering,jee advanced,mathematics,vector algebra,3d geometry,direction cosines and direction ratios
31,177321,engineering $ jee advanced $ mathematics $ vec...,lm205903,engineering,jee advanced,mathematics,vector algebra,3d geometry,system of co-ordinates
32,129093,karnataka board $ 5th karnataka state board $ ...,lm326434,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,skip counting
33,129094,karnataka board $ 5th karnataka state board $ ...,lm326433,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,formation and comparison of numbers
34,129095,karnataka board $ 5th karnataka state board $ ...,lm326432,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,reading and writing five digit numbers
35,129096,karnataka board $ 5th karnataka state board $ ...,lm326431,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,place value of the digits
36,26442,cbse $ 3rd cbse $ environmental studies $ soci...,lm21698,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth
37,27945,cbse $ 3rd cbse $ environmental studies $ soci...,lm20195,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth
38,144452,cbse $ 3rd cbse $ environmental studies $ soci...,lm84337,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth
39,144607,cbse $ 3rd cbse $ environmental studies $ soci...,lm84030,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth
40,148933,cbse $ 3rd cbse $ environmental studies $ soci...,lm47431,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth
41,149088,cbse $ 3rd cbse $ environmental studies $ soci...,lm47276,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth
42,138388,jammu and kashmir board $ 3rd jammu and kashmi...,lm421442,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,design on cloth
43,138389,jammu and kashmir board $ 3rd jammu and kashmi...,lm421441,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,cloth
44,21172,cbse $ 4th cbse $ environmental studies $ life...,lm26968,cbse,4th cbse,environmental studies,life science,a busy month,birds
45,21186,cbse $ 4th cbse $ environmental studies $ life...,lm26954,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest
46,22575,cbse $ 4th cbse $ environmental studies $ life...,lm25565,cbse,4th cbse,environmental studies,life science,a busy month,animals
47,22651,cbse $ 4th cbse $ environmental studies $ life...,lm25489,cbse,4th cbse,environmental studies,life science,a busy month,characteristics of birds
48,144076,cbse $ 4th cbse $ environmental studies $ life...,lm85063,cbse,4th cbse,environmental studies,life science,a busy month,birds
49,144090,cbse $ 4th cbse $ environmental studies $ life...,lm85036,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest

In [10]:
df.tail()

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9
45,21186,cbse $ 4th cbse $ environmental studies $ life...,lm26954,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest
46,22575,cbse $ 4th cbse $ environmental studies $ life...,lm25565,cbse,4th cbse,environmental studies,life science,a busy month,animals
47,22651,cbse $ 4th cbse $ environmental studies $ life...,lm25489,cbse,4th cbse,environmental studies,life science,a busy month,characteristics of birds
48,144076,cbse $ 4th cbse $ environmental studies $ life...,lm85063,cbse,4th cbse,environmental studies,life science,a busy month,birds
49,144090,cbse $ 4th cbse $ environmental studies $ life...,lm85036,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest

In [11]:
df.describe()

             Column1
count      50.000000
mean   108185.780000
std     52043.131821
min     21172.000000
25%     57204.000000
50%    129094.500000
75%    144361.500000
max    177321.000000

In [12]:
require_cols = [3,4,5,6, 7] 

required_df = pd.read_excel(r'C:\Users\Puneet Kumar\Desktop\testing.xlsx', usecols = require_cols) 
print(required_df)

                     Column4                        Column5  \
0           10th foundation                      10th ntse
1           10th foundation                      10th ntse
2           10th foundation                      10th ntse
3           10th foundation                      10th ntse
4           10th foundation                      10th ntse
5           10th foundation                      10th ntse
6           10th foundation                      10th ntse
7                dummy goal             foundation 10 ntse
8                dummy goal             foundation 10 ntse
9                dummy goal             foundation 10 ntse
10               dummy goal             foundation 10 ntse
11               dummy goal             foundation 10 ntse
12               dummy goal             foundation 10 ntse
13              lectureship                ugc net paper 2
14              lectureship                ugc net paper 2
15              lectureship                ugc net paper 2
16              lectureship                ugc net paper 2
17     andhra pradesh board       6th andhra pradesh board
18     andhra pradesh board       6th andhra pradesh board
19     andhra pradesh board       6th andhra pradesh board
20     andhra pradesh board       6th andhra pradesh board
21     andhra pradesh board       6th andhra pradesh board
22     andhra pradesh board       6th andhra pradesh board
23              engineering                   jee advanced
24              engineering                   jee advanced
25              engineering                   jee advanced
26              engineering                   jee advanced
27              engineering                   jee advanced
28              engineering                   jee advanced
29              engineering                   jee advanced
30              engineering                   jee advanced
31              engineering                   jee advanced
32          karnataka board      5th karnataka state board
33          karnataka board      5th karnataka state board
34          karnataka board      5th karnataka state board
35          karnataka board      5th karnataka state board
36                     cbse                       3rd cbse
37                     cbse                       3rd cbse
38                     cbse                       3rd cbse
39                     cbse                       3rd cbse
40                     cbse                       3rd cbse
41                     cbse                       3rd cbse
42  jammu and kashmir board    3rd jammu and kashmir board
43  jammu and kashmir board    3rd jammu and kashmir board
44                     cbse                       4th cbse
45                     cbse                       4th cbse
46                     cbse                       4th cbse
47                     cbse                       4th cbse
48                     cbse                       4th cbse
49                     cbse                       4th cbse

                               Column6            Column7  \
0                         mathematics            algebra
1                         mathematics            algebra
2                         mathematics            algebra
3                         mathematics            algebra
4                         mathematics            algebra
5                         mathematics            algebra
6                         mathematics            algebra
7            scholastic aptitude test            history
8            scholastic aptitude test            history
9            scholastic aptitude test            history
10           scholastic aptitude test            history
11           scholastic aptitude test            history
12           scholastic aptitude test            history
13                               urdu    تاریخ زبان اردو
14                            chinese             现代汉语语法
15   arab culture and islamic studies     islam in india
16   arab culture and islamic studies     islam in india
17                        mathematics           geometry
18                        mathematics           geometry
19                        mathematics           geometry
20                        mathematics           geometry
21                        mathematics           geometry
22                        mathematics           geometry
23                        mathematics     vector algebra
24                        mathematics     vector algebra
25                        mathematics     vector algebra
26                        mathematics     vector algebra
27                        mathematics     vector algebra
28                        mathematics     vector algebra
29                        mathematics     vector algebra
30                        mathematics     vector algebra
31                        mathematics     vector algebra
32                        mathematics         arithmetic
33                        mathematics         arithmetic
34                        mathematics         arithmetic
35                        mathematics         arithmetic
36              environmental studies     social science
37              environmental studies     social science
38              environmental studies     social science
39              environmental studies     social science
40              environmental studies     social science
41              environmental studies     social science
42              environmental studies     social science
43              environmental studies     social science
44              environmental studies       life science
45              environmental studies       life science
46              environmental studies       life science
47              environmental studies       life science
48              environmental studies       life science
49              environmental studies       life science

                                              Column8
0                  "linear equations in one variable
1                  "linear equations in one variable
2                  "linear equations in one variable
3                  "linear equations in one variable
4                  "linear equations in one variable
5                  "linear equations in one variable
6                  "linear equations in one variable
7               "the rise of nationalism in europe "
8               "the rise of nationalism in europe "
9               "the rise of nationalism in europe "
10              "the rise of nationalism in europe "
11              "the rise of nationalism in europe "
12              "the rise of nationalism in europe "
13                               ، پراکرت و اپ بھرنش
14                                               ‘把’
15       1757: british colonialism and its expansion
16   1857: first war of independence and its conse...
17                                    2d - 3d shapes
18                                    2d - 3d shapes
19                                    2d - 3d shapes
20                                    2d - 3d shapes
21                                    2d - 3d shapes
22                                    2d - 3d shapes
23                                       3d geometry
24                                       3d geometry
25                                       3d geometry
26                                       3d geometry
27                                       3d geometry
28                                       3d geometry
29                                       3d geometry
30                                       3d geometry
31                                       3d geometry
32                                 5 - digit numbers
33                                 5 - digit numbers
34                                 5 - digit numbers
35                                 5 - digit numbers
36                                 a beautiful cloth
37                                 a beautiful cloth
38                                 a beautiful cloth
39                                 a beautiful cloth
40                                 a beautiful cloth
41                                 a beautiful cloth
42                                 a beautiful cloth
43                                 a beautiful cloth
44                                      a busy month
45                                      a busy month
46                                      a busy month
47                                      a busy month
48                                      a busy month
49                                      a busy month

In [13]:
import sys
import pprint
pprint.pprint(sys.path)

['C:\\Users\\Puneet Kumar\\Desktop\\Untitled Folder',
 'C:\\Users\\Puneet Kumar\\anaconda3\\python38.zip',
 'C:\\Users\\Puneet Kumar\\anaconda3\\DLLs',
 'C:\\Users\\Puneet Kumar\\anaconda3\\lib',
 'C:\\Users\\Puneet Kumar\\anaconda3',
 '',
 'C:\\Users\\Puneet Kumar\\anaconda3\\lib\\site-packages',
 'C:\\Users\\Puneet Kumar\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Puneet Kumar\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Puneet Kumar\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Puneet Kumar\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Puneet Kumar\\.ipython']

In [14]:
pwd

'C:\\Users\\Puneet Kumar\\Desktop\\Untitled Folder'

In [17]:
df.columns

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8', 'Column9'],
      dtype='object')

In [9]:
df.groupby(['Column4', 'Column5', 'Column6',
       'Column7', 'Column8'])

In [10]:
print( df.groupby(['Column4', 'Column5', 'Column6',
       'Column7', 'Column8']).groups)

{('10th foundation ', ' 10th ntse ', ' mathematics ', ' algebra ', ' "linear equations in one variable '): [0, 1, 2, 3, 4, 5, 6], ('andhra pradesh board ', ' 6th andhra pradesh board ', ' mathematics ', ' geometry ', ' 2d - 3d shapes '): [17, 18, 19, 20, 21, 22], ('cbse ', ' 3rd cbse ', ' environmental studies ', ' social science ', ' a beautiful cloth '): [36, 37, 38, 39, 40, 41], ('cbse ', ' 4th cbse ', ' environmental studies ', ' life science ', ' a busy month '): [44, 45, 46, 47, 48, 49], ('dummy goal ', ' foundation 10 ntse ', ' scholastic aptitude test ', ' history ', ' "the rise of nationalism in europe " '): [7, 8, 9, 10, 11, 12], ('engineering ', ' jee advanced ', ' mathematics ', ' vector algebra ', ' 3d geometry '): [23, 24, 25, 26, 27, 28, 29, 30, 31], ('jammu and kashmir board ', ' 3rd jammu and kashmir board ', ' environmental studies ', ' social science ', ' a beautiful cloth '): [42, 43], ('karnataka board ', ' 5th karnataka state board ', ' mathematics ', ' arithmetic ', ' 5 - digit numbers '): [32, 33, 34, 35], ('lectureship ', ' ugc net paper 2 ', ' arab culture and islamic studies ', ' islam in india ', ' 1757: british colonialism and its expansion '): [15], ('lectureship ', ' ugc net paper 2 ', ' arab culture and islamic studies ', ' islam in india ', ' 1857: first war of independence and its consequences '): [16], ('lectureship ', ' ugc net paper 2 ', ' chinese ', ' 现代汉语语法 ', ' ‘把’ '): [14], ('lectureship ', ' ugc net paper 2 ', ' urdu ', ' تاریخ زبان اردو ', ' ، پراکرت و اپ بھرنش '): [13]}

In [11]:
a = df.groupby(['Column4', 'Column5', 'Column6',
       'Column7', 'Column8'])

In [12]:
print(a['Column8'])

<pandas.core.groupby.generic.SeriesGroupBy object at 0x000002EF68FA50D0>

In [34]:
a['Column8'].apply(list)

Column4                   Column5                        Column6                             Column7            Column8
10th foundation            10th ntse                      mathematics                         algebra            "linear equations in one variable                        [ "linear equations in one variable ,  "linear...
andhra pradesh board       6th andhra pradesh board       mathematics                         geometry           2d - 3d shapes                                           [ 2d - 3d shapes ,  2d - 3d shapes ,  2d - 3d ...
cbse                       3rd cbse                       environmental studies               social science     a beautiful cloth                                        [ a beautiful cloth ,  a beautiful cloth ,  a ...
                           4th cbse                       environmental studies               life science       a busy month                                             [ a busy month ,  a busy month ,  a busy month...
dummy goal                 foundation 10 ntse             scholastic aptitude test            history            "the rise of nationalism in europe "                     [ "the rise of nationalism in europe " ,  "the...
engineering                jee advanced                   mathematics                         vector algebra     3d geometry                                              [ 3d geometry ,  3d geometry ,  3d geometry , ...
jammu and kashmir board    3rd jammu and kashmir board    environmental studies               social science     a beautiful cloth                                               [ a beautiful cloth ,  a beautiful cloth ]
karnataka board            5th karnataka state board      mathematics                         arithmetic         5 - digit numbers                                        [ 5 - digit numbers ,  5 - digit numbers ,  5 ...
lectureship                ugc net paper 2                arab culture and islamic studies    islam in india     1757: british colonialism and its expansion                [ 1757: british colonialism and its expansion ]
                                                                                                                 1857: first war of independence and its consequences     [ 1857: first war of independence and its cons...
                                                          chinese                             现代汉语语法             ‘把’                                                                                                [ ‘把’ ]
                                                          urdu                                تاریخ زبان اردو    ، پراکرت و اپ بھرنش                                                                [ ، پراکرت و اپ بھرنش ]
Name: Column8, dtype: object

In [13]:
for names, grp in a['Column9']:
    print(names)
    print(grp)

('10th foundation ', ' 10th ntse ', ' mathematics ', ' algebra ', ' "linear equations in one variable ')
0               equations reducible to the linear form
1                   reducing equations to simpler form
2                               some more applications
3     solving equations having the variable on both...
4                                    some applications
5     solving equations which have linear expressio...
6        introduction linear equations in one variable
Name: Column9, dtype: object
('andhra pradesh board ', ' 6th andhra pradesh board ', ' mathematics ', ' geometry ', ' 2d - 3d shapes ')
17        understanding of 3d shapes
18                          symmetry
19            introduction of circle
20     introduction of quadrilateral
21                          polygons
22          introduction of triangle
Name: Column9, dtype: object
('cbse ', ' 3rd cbse ', ' environmental studies ', ' social science ', ' a beautiful cloth ')
36     design on cloth
37               cloth
38     design on cloth
39               cloth
40     design on cloth
41               cloth
Name: Column9, dtype: object
('cbse ', ' 4th cbse ', ' environmental studies ', ' life science ', ' a busy month ')
44                        birds
45                  bird's nest
46                      animals
47     characteristics of birds
48                        birds
49                  bird's nest
Name: Column9, dtype: object
('dummy goal ', ' foundation 10 ntse ', ' scholastic aptitude test ', ' history ', ' "the rise of nationalism in europe " ')
7                                                greece
8                                     italy and germany
9                                               hungray
10     general characteristics of the movements in p...
11                    the ideas of gluseppe mazzini etc
12     the growth of nationalism in europe after the...
Name: Column9, dtype: object
('engineering ', ' jee advanced ', ' mathematics ', ' vector algebra ', ' 3d geometry ')
23                   geometrical applications
24                        planes and geometry
25                             straight lines
26                           points and plane
27                             line and plane
28        equation of line in different forms
29                                      plane
30     direction cosines and direction ratios
31                     system of co-ordinates
Name: Column9, dtype: object
('jammu and kashmir board ', ' 3rd jammu and kashmir board ', ' environmental studies ', ' social science ', ' a beautiful cloth ')
42     design on cloth
43               cloth
Name: Column9, dtype: object
('karnataka board ', ' 5th karnataka state board ', ' mathematics ', ' arithmetic ', ' 5 - digit numbers ')
32                              skip counting
33        formation and comparison of numbers
34     reading and writing five digit numbers
35                  place value of the digits
Name: Column9, dtype: object
('lectureship ', ' ugc net paper 2 ', ' arab culture and islamic studies ', ' islam in india ', ' 1757: british colonialism and its expansion ')
15     1757: british colonialism and its expansion
Name: Column9, dtype: object
('lectureship ', ' ugc net paper 2 ', ' arab culture and islamic studies ', ' islam in india ', ' 1857: first war of independence and its consequences ')
16     1857: first war of independence and its conse...
Name: Column9, dtype: object
('lectureship ', ' ugc net paper 2 ', ' chinese ', ' 现代汉语语法 ', ' ‘把’ ')
14     句法
Name: Column9, dtype: object
('lectureship ', ' ugc net paper 2 ', ' urdu ', ' تاریخ زبان اردو ', ' ، پراکرت و اپ بھرنش ')
13     ، پراکرت و اپ بھرنش
Name: Column9, dtype: object

In [50]:
for ii, (names, grp) in enumerate(a['Column9']) :
        print(names)
        print(ii)


        print(grp)
#         print(grp.index)

('10th foundation ', ' 10th ntse ', ' mathematics ', ' algebra ', ' "linear equations in one variable ')
0
0               equations reducible to the linear form
1                   reducing equations to simpler form
2                               some more applications
3     solving equations having the variable on both...
4                                    some applications
5     solving equations which have linear expressio...
6        introduction linear equations in one variable
Name: Column9, dtype: object
('andhra pradesh board ', ' 6th andhra pradesh board ', ' mathematics ', ' geometry ', ' 2d - 3d shapes ')
1
17        understanding of 3d shapes
18                          symmetry
19            introduction of circle
20     introduction of quadrilateral
21                          polygons
22          introduction of triangle
Name: Column9, dtype: object
('cbse ', ' 3rd cbse ', ' environmental studies ', ' social science ', ' a beautiful cloth ')
2
36     design on cloth
37               cloth
38     design on cloth
39               cloth
40     design on cloth
41               cloth
Name: Column9, dtype: object
('cbse ', ' 4th cbse ', ' environmental studies ', ' life science ', ' a busy month ')
3
44                        birds
45                  bird's nest
46                      animals
47     characteristics of birds
48                        birds
49                  bird's nest
Name: Column9, dtype: object
('dummy goal ', ' foundation 10 ntse ', ' scholastic aptitude test ', ' history ', ' "the rise of nationalism in europe " ')
4
7                                                greece
8                                     italy and germany
9                                               hungray
10     general characteristics of the movements in p...
11                    the ideas of gluseppe mazzini etc
12     the growth of nationalism in europe after the...
Name: Column9, dtype: object
('engineering ', ' jee advanced ', ' mathematics ', ' vector algebra ', ' 3d geometry ')
5
23                   geometrical applications
24                        planes and geometry
25                             straight lines
26                           points and plane
27                             line and plane
28        equation of line in different forms
29                                      plane
30     direction cosines and direction ratios
31                     system of co-ordinates
Name: Column9, dtype: object
('jammu and kashmir board ', ' 3rd jammu and kashmir board ', ' environmental studies ', ' social science ', ' a beautiful cloth ')
6
42     design on cloth
43               cloth
Name: Column9, dtype: object
('karnataka board ', ' 5th karnataka state board ', ' mathematics ', ' arithmetic ', ' 5 - digit numbers ')
7
32                              skip counting
33        formation and comparison of numbers
34     reading and writing five digit numbers
35                  place value of the digits
Name: Column9, dtype: object
('lectureship ', ' ugc net paper 2 ', ' arab culture and islamic studies ', ' islam in india ', ' 1757: british colonialism and its expansion ')
8
15     1757: british colonialism and its expansion
Name: Column9, dtype: object
('lectureship ', ' ugc net paper 2 ', ' arab culture and islamic studies ', ' islam in india ', ' 1857: first war of independence and its consequences ')
9
16     1857: first war of independence and its conse...
Name: Column9, dtype: object
('lectureship ', ' ugc net paper 2 ', ' chinese ', ' 现代汉语语法 ', ' ‘把’ ')
10
14     句法
Name: Column9, dtype: object
('lectureship ', ' ugc net paper 2 ', ' urdu ', ' تاریخ زبان اردو ', ' ، پراکرت و اپ بھرنش ')
11
13     ، پراکرت و اپ بھرنش
Name: Column9, dtype: object

In [14]:
df

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9
0,51415,10th foundation $ 10th ntse $ mathematics $ al...,lm193876,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",equations reducible to the linear form
1,51416,10th foundation $ 10th ntse $ mathematics $ al...,lm193875,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",reducing equations to simpler form
2,51417,10th foundation $ 10th ntse $ mathematics $ al...,lm193873,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some more applications
3,51418,10th foundation $ 10th ntse $ mathematics $ al...,lm193871,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations having the variable on both...
4,51419,10th foundation $ 10th ntse $ mathematics $ al...,lm193869,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some applications
5,51420,10th foundation $ 10th ntse $ mathematics $ al...,lm193867,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations which have linear expressio...
6,51421,10th foundation $ 10th ntse $ mathematics $ al...,lm193865,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",introduction linear equations in one variable
7,74553,dummy goal $ foundation 10 ntse $ scholastic a...,lm218868,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,greece
8,74554,dummy goal $ foundation 10 ntse $ scholastic a...,lm218867,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,italy and germany
9,74555,dummy goal $ foundation 10 ntse $ scholastic a...,lm218866,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,hungray
10,74556,dummy goal $ foundation 10 ntse $ scholastic a...,lm218865,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,general characteristics of the movements in p...
11,74557,dummy goal $ foundation 10 ntse $ scholastic a...,lm218864,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the ideas of gluseppe mazzini etc
12,74558,dummy goal $ foundation 10 ntse $ scholastic a...,lm218863,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the growth of nationalism in europe after the...
13,95325,lectureship $ ugc net paper 2 $ urdu $ تاریخ ز...,lm522197,lectureship,ugc net paper 2,urdu,تاریخ زبان اردو,، پراکرت و اپ بھرنش,، پراکرت و اپ بھرنش
14,93516,lectureship $ ugc net paper 2 $ chinese $ 现代汉语...,lm541533,lectureship,ugc net paper 2,chinese,现代汉语语法,‘把’,句法
15,95589,lectureship $ ugc net paper 2 $ arab culture a...,lm402639,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1757: british colonialism and its expansion,1757: british colonialism and its expansion
16,95588,lectureship $ ugc net paper 2 $ arab culture a...,lm402640,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1857: first war of independence and its conse...,1857: first war of independence and its conse...
17,135962,andhra pradesh board $ 6th andhra pradesh boar...,lm483641,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,understanding of 3d shapes
18,135963,andhra pradesh board $ 6th andhra pradesh boar...,lm483640,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,symmetry
19,135964,andhra pradesh board $ 6th andhra pradesh boar...,lm483639,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of circle
20,135965,andhra pradesh board $ 6th andhra pradesh boar...,lm483638,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of quadrilateral
21,135966,andhra pradesh board $ 6th andhra pradesh boar...,lm483637,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,polygons
22,135967,andhra pradesh board $ 6th andhra pradesh boar...,lm483636,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of triangle
23,177313,engineering $ jee advanced $ mathematics $ vec...,lm205920,engineering,jee advanced,mathematics,vector algebra,3d geometry,geometrical applications
24,177314,engineering $ jee advanced $ mathematics $ vec...,lm205918,engineering,jee advanced,mathematics,vector algebra,3d geometry,planes and geometry
25,177315,engineering $ jee advanced $ mathematics $ vec...,lm205916,engineering,jee advanced,mathematics,vector algebra,3d geometry,straight lines
26,177316,engineering $ jee advanced $ mathematics $ vec...,lm205913,engineering,jee advanced,mathematics,vector algebra,3d geometry,points and plane
27,177317,engineering $ jee advanced $ mathematics $ vec...,lm205911,engineering,jee advanced,mathematics,vector algebra,3d geometry,line and plane
28,177318,engineering $ jee advanced $ mathematics $ vec...,lm205909,engineering,jee advanced,mathematics,vector algebra,3d geometry,equation of line in different forms
29,177319,engineering $ jee advanced $ mathematics $ vec...,lm205907,engineering,jee advanced,mathematics,vector algebra,3d geometry,plane
30,177320,engineering $ jee advanced $ mathematics $ vec...,lm205905,engineering,jee advanced,mathematics,vector algebra,3d geometry,direction cosines and direction ratios
31,177321,engineering $ jee advanced $ mathematics $ vec...,lm205903,engineering,jee advanced,mathematics,vector algebra,3d geometry,system of co-ordinates
32,129093,karnataka board $ 5th karnataka state board $ ...,lm326434,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,skip counting
33,129094,karnataka board $ 5th karnataka state board $ ...,lm326433,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,formation and comparison of numbers
34,129095,karnataka board $ 5th karnataka state board $ ...,lm326432,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,reading and writing five digit numbers
35,129096,karnataka board $ 5th karnataka state board $ ...,lm326431,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,place value of the digits
36,26442,cbse $ 3rd cbse $ environmental studies $ soci...,lm21698,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth
37,27945,cbse $ 3rd cbse $ environmental studies $ soci...,lm20195,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth
38,144452,cbse $ 3rd cbse $ environmental studies $ soci...,lm84337,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth
39,144607,cbse $ 3rd cbse $ environmental studies $ soci...,lm84030,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth
40,148933,cbse $ 3rd cbse $ environmental studies $ soci...,lm47431,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth
41,149088,cbse $ 3rd cbse $ environmental studies $ soci...,lm47276,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth
42,138388,jammu and kashmir board $ 3rd jammu and kashmi...,lm421442,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,design on cloth
43,138389,jammu and kashmir board $ 3rd jammu and kashmi...,lm421441,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,cloth
44,21172,cbse $ 4th cbse $ environmental studies $ life...,lm26968,cbse,4th cbse,environmental studies,life science,a busy month,birds
45,21186,cbse $ 4th cbse $ environmental studies $ life...,lm26954,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest
46,22575,cbse $ 4th cbse $ environmental studies $ life...,lm25565,cbse,4th cbse,environmental studies,life science,a busy month,animals
47,22651,cbse $ 4th cbse $ environmental studies $ life...,lm25489,cbse,4th cbse,environmental studies,life science,a busy month,characteristics of birds
48,144076,cbse $ 4th cbse $ environmental studies $ life...,lm85063,cbse,4th cbse,environmental studies,life science,a busy month,birds
49,144090,cbse $ 4th cbse $ environmental studies $ life...,lm85036,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest

In [15]:
[(idx,key)  for key,value in df.groupby(['Column4', 'Column5', 'Column6',
       'Column7', 'Column8'])['Column1'].apply(list).reset_index()['Column1'].to_dict().items() for idx in value ]

[(51415, 0),
 (51416, 0),
 (51417, 0),
 (51418, 0),
 (51419, 0),
 (51420, 0),
 (51421, 0),
 (135962, 1),
 (135963, 1),
 (135964, 1),
 (135965, 1),
 (135966, 1),
 (135967, 1),
 (26442, 2),
 (27945, 2),
 (144452, 2),
 (144607, 2),
 (148933, 2),
 (149088, 2),
 (21172, 3),
 (21186, 3),
 (22575, 3),
 (22651, 3),
 (144076, 3),
 (144090, 3),
 (74553, 4),
 (74554, 4),
 (74555, 4),
 (74556, 4),
 (74557, 4),
 (74558, 4),
 (177313, 5),
 (177314, 5),
 (177315, 5),
 (177316, 5),
 (177317, 5),
 (177318, 5),
 (177319, 5),
 (177320, 5),
 (177321, 5),
 (138388, 6),
 (138389, 6),
 (129093, 7),
 (129094, 7),
 (129095, 7),
 (129096, 7),
 (95589, 8),
 (95588, 9),
 (93516, 10),
 (95325, 11)]

In [65]:
pd.DataFrame([(idx,key)  for key,value in df.groupby(['Column4', 'Column5', 'Column6',
       'Column7', 'Column8'])['Column1'].apply(list).reset_index()['Column1'].to_dict().items() for idx in value ]).set_index([0])

         1
0
51415    0
51416    0
51417    0
51418    0
51419    0
51420    0
51421    0
135962   1
135963   1
135964   1
135965   1
135966   1
135967   1
26442    2
27945    2
144452   2
144607   2
148933   2
149088   2
21172    3
21186    3
22575    3
22651    3
144076   3
144090   3
74553    4
74554    4
74555    4
74556    4
74557    4
74558    4
177313   5
177314   5
177315   5
177316   5
177317   5
177318   5
177319   5
177320   5
177321   5
138388   6
138389   6
129093   7
129094   7
129095   7
129096   7
95589    8
95588    9
93516   10
95325   11

In [16]:
df.join(pd.DataFrame([(idx,key)  for key,value in df.groupby(['Column4', 'Column5', 'Column6',
       'Column7', 'Column8'])['Column1'].apply(list).reset_index()['Column1'].to_dict().items() for idx in value ],columns=[0,'Column10']).set_index([0]),on=['Column1'])

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10
0,51415,10th foundation $ 10th ntse $ mathematics $ al...,lm193876,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",equations reducible to the linear form,0
1,51416,10th foundation $ 10th ntse $ mathematics $ al...,lm193875,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",reducing equations to simpler form,0
2,51417,10th foundation $ 10th ntse $ mathematics $ al...,lm193873,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some more applications,0
3,51418,10th foundation $ 10th ntse $ mathematics $ al...,lm193871,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations having the variable on both...,0
4,51419,10th foundation $ 10th ntse $ mathematics $ al...,lm193869,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some applications,0
5,51420,10th foundation $ 10th ntse $ mathematics $ al...,lm193867,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations which have linear expressio...,0
6,51421,10th foundation $ 10th ntse $ mathematics $ al...,lm193865,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",introduction linear equations in one variable,0
7,74553,dummy goal $ foundation 10 ntse $ scholastic a...,lm218868,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,greece,4
8,74554,dummy goal $ foundation 10 ntse $ scholastic a...,lm218867,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,italy and germany,4
9,74555,dummy goal $ foundation 10 ntse $ scholastic a...,lm218866,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,hungray,4
10,74556,dummy goal $ foundation 10 ntse $ scholastic a...,lm218865,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,general characteristics of the movements in p...,4
11,74557,dummy goal $ foundation 10 ntse $ scholastic a...,lm218864,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the ideas of gluseppe mazzini etc,4
12,74558,dummy goal $ foundation 10 ntse $ scholastic a...,lm218863,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the growth of nationalism in europe after the...,4
13,95325,lectureship $ ugc net paper 2 $ urdu $ تاریخ ز...,lm522197,lectureship,ugc net paper 2,urdu,تاریخ زبان اردو,، پراکرت و اپ بھرنش,، پراکرت و اپ بھرنش,11
14,93516,lectureship $ ugc net paper 2 $ chinese $ 现代汉语...,lm541533,lectureship,ugc net paper 2,chinese,现代汉语语法,‘把’,句法,10
15,95589,lectureship $ ugc net paper 2 $ arab culture a...,lm402639,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1757: british colonialism and its expansion,1757: british colonialism and its expansion,8
16,95588,lectureship $ ugc net paper 2 $ arab culture a...,lm402640,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1857: first war of independence and its conse...,1857: first war of independence and its conse...,9
17,135962,andhra pradesh board $ 6th andhra pradesh boar...,lm483641,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,understanding of 3d shapes,1
18,135963,andhra pradesh board $ 6th andhra pradesh boar...,lm483640,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,symmetry,1
19,135964,andhra pradesh board $ 6th andhra pradesh boar...,lm483639,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of circle,1
20,135965,andhra pradesh board $ 6th andhra pradesh boar...,lm483638,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of quadrilateral,1
21,135966,andhra pradesh board $ 6th andhra pradesh boar...,lm483637,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,polygons,1
22,135967,andhra pradesh board $ 6th andhra pradesh boar...,lm483636,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of triangle,1
23,177313,engineering $ jee advanced $ mathematics $ vec...,lm205920,engineering,jee advanced,mathematics,vector algebra,3d geometry,geometrical applications,5
24,177314,engineering $ jee advanced $ mathematics $ vec...,lm205918,engineering,jee advanced,mathematics,vector algebra,3d geometry,planes and geometry,5
25,177315,engineering $ jee advanced $ mathematics $ vec...,lm205916,engineering,jee advanced,mathematics,vector algebra,3d geometry,straight lines,5
26,177316,engineering $ jee advanced $ mathematics $ vec...,lm205913,engineering,jee advanced,mathematics,vector algebra,3d geometry,points and plane,5
27,177317,engineering $ jee advanced $ mathematics $ vec...,lm205911,engineering,jee advanced,mathematics,vector algebra,3d geometry,line and plane,5
28,177318,engineering $ jee advanced $ mathematics $ vec...,lm205909,engineering,jee advanced,mathematics,vector algebra,3d geometry,equation of line in different forms,5
29,177319,engineering $ jee advanced $ mathematics $ vec...,lm205907,engineering,jee advanced,mathematics,vector algebra,3d geometry,plane,5
30,177320,engineering $ jee advanced $ mathematics $ vec...,lm205905,engineering,jee advanced,mathematics,vector algebra,3d geometry,direction cosines and direction ratios,5
31,177321,engineering $ jee advanced $ mathematics $ vec...,lm205903,engineering,jee advanced,mathematics,vector algebra,3d geometry,system of co-ordinates,5
32,129093,karnataka board $ 5th karnataka state board $ ...,lm326434,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,skip counting,7
33,129094,karnataka board $ 5th karnataka state board $ ...,lm326433,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,formation and comparison of numbers,7
34,129095,karnataka board $ 5th karnataka state board $ ...,lm326432,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,reading and writing five digit numbers,7
35,129096,karnataka board $ 5th karnataka state board $ ...,lm326431,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,place value of the digits,7
36,26442,cbse $ 3rd cbse $ environmental studies $ soci...,lm21698,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,2
37,27945,cbse $ 3rd cbse $ environmental studies $ soci...,lm20195,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth,2
38,144452,cbse $ 3rd cbse $ environmental studies $ soci...,lm84337,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,2
39,144607,cbse $ 3rd cbse $ environmental studies $ soci...,lm84030,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth,2
40,148933,cbse $ 3rd cbse $ environmental studies $ soci...,lm47431,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,2
41,149088,cbse $ 3rd cbse $ environmental studies $ soci...,lm47276,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth,2
42,138388,jammu and kashmir board $ 3rd jammu and kashmi...,lm421442,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,design on cloth,6
43,138389,jammu and kashmir board $ 3rd jammu and kashmi...,lm421441,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,cloth,6
44,21172,cbse $ 4th cbse $ environmental studies $ life...,lm26968,cbse,4th cbse,environmental studies,life science,a busy month,birds,3
45,21186,cbse $ 4th cbse $ environmental studies $ life...,lm26954,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest,3
46,22575,cbse $ 4th cbse $ environmental studies $ life...,lm25565,cbse,4th cbse,environmental studies,life science,a busy month,animals,3
47,22651,cbse $ 4th cbse $ environmental studies $ life...,lm25489,cbse,4th cbse,environmental studies,life science,a busy month,characteristics of birds,3
48,144076,cbse $ 4th cbse $ environmental studies $ life...,lm85063,cbse,4th cbse,environmental studies,life science,a busy month,birds,3
49,144090,cbse $ 4th cbse $ environmental studies $ life...,lm85036,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest,3

In [46]:
df

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9
0,51415,10th foundation $ 10th ntse $ mathematics $ al...,lm193876,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",equations reducible to the linear form
1,51416,10th foundation $ 10th ntse $ mathematics $ al...,lm193875,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",reducing equations to simpler form
2,51417,10th foundation $ 10th ntse $ mathematics $ al...,lm193873,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some more applications
3,51418,10th foundation $ 10th ntse $ mathematics $ al...,lm193871,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations having the variable on both...
4,51419,10th foundation $ 10th ntse $ mathematics $ al...,lm193869,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some applications
5,51420,10th foundation $ 10th ntse $ mathematics $ al...,lm193867,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations which have linear expressio...
6,51421,10th foundation $ 10th ntse $ mathematics $ al...,lm193865,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",introduction linear equations in one variable
7,74553,dummy goal $ foundation 10 ntse $ scholastic a...,lm218868,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,greece
8,74554,dummy goal $ foundation 10 ntse $ scholastic a...,lm218867,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,italy and germany
9,74555,dummy goal $ foundation 10 ntse $ scholastic a...,lm218866,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,hungray
10,74556,dummy goal $ foundation 10 ntse $ scholastic a...,lm218865,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,general characteristics of the movements in p...
11,74557,dummy goal $ foundation 10 ntse $ scholastic a...,lm218864,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the ideas of gluseppe mazzini etc
12,74558,dummy goal $ foundation 10 ntse $ scholastic a...,lm218863,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the growth of nationalism in europe after the...
13,95325,lectureship $ ugc net paper 2 $ urdu $ تاریخ ز...,lm522197,lectureship,ugc net paper 2,urdu,تاریخ زبان اردو,، پراکرت و اپ بھرنش,، پراکرت و اپ بھرنش
14,93516,lectureship $ ugc net paper 2 $ chinese $ 现代汉语...,lm541533,lectureship,ugc net paper 2,chinese,现代汉语语法,‘把’,句法
15,95589,lectureship $ ugc net paper 2 $ arab culture a...,lm402639,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1757: british colonialism and its expansion,1757: british colonialism and its expansion
16,95588,lectureship $ ugc net paper 2 $ arab culture a...,lm402640,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1857: first war of independence and its conse...,1857: first war of independence and its conse...
17,135962,andhra pradesh board $ 6th andhra pradesh boar...,lm483641,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,understanding of 3d shapes
18,135963,andhra pradesh board $ 6th andhra pradesh boar...,lm483640,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,symmetry
19,135964,andhra pradesh board $ 6th andhra pradesh boar...,lm483639,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of circle
20,135965,andhra pradesh board $ 6th andhra pradesh boar...,lm483638,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of quadrilateral
21,135966,andhra pradesh board $ 6th andhra pradesh boar...,lm483637,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,polygons
22,135967,andhra pradesh board $ 6th andhra pradesh boar...,lm483636,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of triangle
23,177313,engineering $ jee advanced $ mathematics $ vec...,lm205920,engineering,jee advanced,mathematics,vector algebra,3d geometry,geometrical applications
24,177314,engineering $ jee advanced $ mathematics $ vec...,lm205918,engineering,jee advanced,mathematics,vector algebra,3d geometry,planes and geometry
25,177315,engineering $ jee advanced $ mathematics $ vec...,lm205916,engineering,jee advanced,mathematics,vector algebra,3d geometry,straight lines
26,177316,engineering $ jee advanced $ mathematics $ vec...,lm205913,engineering,jee advanced,mathematics,vector algebra,3d geometry,points and plane
27,177317,engineering $ jee advanced $ mathematics $ vec...,lm205911,engineering,jee advanced,mathematics,vector algebra,3d geometry,line and plane
28,177318,engineering $ jee advanced $ mathematics $ vec...,lm205909,engineering,jee advanced,mathematics,vector algebra,3d geometry,equation of line in different forms
29,177319,engineering $ jee advanced $ mathematics $ vec...,lm205907,engineering,jee advanced,mathematics,vector algebra,3d geometry,plane
30,177320,engineering $ jee advanced $ mathematics $ vec...,lm205905,engineering,jee advanced,mathematics,vector algebra,3d geometry,direction cosines and direction ratios
31,177321,engineering $ jee advanced $ mathematics $ vec...,lm205903,engineering,jee advanced,mathematics,vector algebra,3d geometry,system of co-ordinates
32,129093,karnataka board $ 5th karnataka state board $ ...,lm326434,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,skip counting
33,129094,karnataka board $ 5th karnataka state board $ ...,lm326433,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,formation and comparison of numbers
34,129095,karnataka board $ 5th karnataka state board $ ...,lm326432,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,reading and writing five digit numbers
35,129096,karnataka board $ 5th karnataka state board $ ...,lm326431,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,place value of the digits
36,26442,cbse $ 3rd cbse $ environmental studies $ soci...,lm21698,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth
37,27945,cbse $ 3rd cbse $ environmental studies $ soci...,lm20195,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth
38,144452,cbse $ 3rd cbse $ environmental studies $ soci...,lm84337,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth
39,144607,cbse $ 3rd cbse $ environmental studies $ soci...,lm84030,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth
40,148933,cbse $ 3rd cbse $ environmental studies $ soci...,lm47431,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth
41,149088,cbse $ 3rd cbse $ environmental studies $ soci...,lm47276,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth
42,138388,jammu and kashmir board $ 3rd jammu and kashmi...,lm421442,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,design on cloth
43,138389,jammu and kashmir board $ 3rd jammu and kashmi...,lm421441,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,cloth
44,21172,cbse $ 4th cbse $ environmental studies $ life...,lm26968,cbse,4th cbse,environmental studies,life science,a busy month,birds
45,21186,cbse $ 4th cbse $ environmental studies $ life...,lm26954,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest
46,22575,cbse $ 4th cbse $ environmental studies $ life...,lm25565,cbse,4th cbse,environmental studies,life science,a busy month,animals
47,22651,cbse $ 4th cbse $ environmental studies $ life...,lm25489,cbse,4th cbse,environmental studies,life science,a busy month,characteristics of birds
48,144076,cbse $ 4th cbse $ environmental studies $ life...,lm85063,cbse,4th cbse,environmental studies,life science,a busy month,birds
49,144090,cbse $ 4th cbse $ environmental studies $ life...,lm85036,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest

In [47]:
a = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

In [48]:
z=dict(enumerate([i+j+k+l for i in a for j in a for k in a for l in a]))

In [49]:
b = df.join(pd.DataFrame([(idx,key)  for key,value in df.groupby(['Column4', 'Column5', 'Column6',
       'Column7', 'Column8'])['Column1'].apply(list).reset_index()['Column1'].to_dict().items() for idx in value ],columns=[0,'Column10']).set_index([0]),on=['Column1'])

In [50]:
b['Column10']=b['Column10'].map(z)

In [51]:
b

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10
0,51415,10th foundation $ 10th ntse $ mathematics $ al...,lm193876,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",equations reducible to the linear form,AAAA
1,51416,10th foundation $ 10th ntse $ mathematics $ al...,lm193875,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",reducing equations to simpler form,AAAA
2,51417,10th foundation $ 10th ntse $ mathematics $ al...,lm193873,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some more applications,AAAA
3,51418,10th foundation $ 10th ntse $ mathematics $ al...,lm193871,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations having the variable on both...,AAAA
4,51419,10th foundation $ 10th ntse $ mathematics $ al...,lm193869,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some applications,AAAA
5,51420,10th foundation $ 10th ntse $ mathematics $ al...,lm193867,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations which have linear expressio...,AAAA
6,51421,10th foundation $ 10th ntse $ mathematics $ al...,lm193865,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",introduction linear equations in one variable,AAAA
7,74553,dummy goal $ foundation 10 ntse $ scholastic a...,lm218868,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,greece,AAAE
8,74554,dummy goal $ foundation 10 ntse $ scholastic a...,lm218867,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,italy and germany,AAAE
9,74555,dummy goal $ foundation 10 ntse $ scholastic a...,lm218866,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,hungray,AAAE
10,74556,dummy goal $ foundation 10 ntse $ scholastic a...,lm218865,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,general characteristics of the movements in p...,AAAE
11,74557,dummy goal $ foundation 10 ntse $ scholastic a...,lm218864,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the ideas of gluseppe mazzini etc,AAAE
12,74558,dummy goal $ foundation 10 ntse $ scholastic a...,lm218863,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the growth of nationalism in europe after the...,AAAE
13,95325,lectureship $ ugc net paper 2 $ urdu $ تاریخ ز...,lm522197,lectureship,ugc net paper 2,urdu,تاریخ زبان اردو,، پراکرت و اپ بھرنش,، پراکرت و اپ بھرنش,AAAL
14,93516,lectureship $ ugc net paper 2 $ chinese $ 现代汉语...,lm541533,lectureship,ugc net paper 2,chinese,现代汉语语法,‘把’,句法,AAAK
15,95589,lectureship $ ugc net paper 2 $ arab culture a...,lm402639,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1757: british colonialism and its expansion,1757: british colonialism and its expansion,AAAI
16,95588,lectureship $ ugc net paper 2 $ arab culture a...,lm402640,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1857: first war of independence and its conse...,1857: first war of independence and its conse...,AAAJ
17,135962,andhra pradesh board $ 6th andhra pradesh boar...,lm483641,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,understanding of 3d shapes,AAAB
18,135963,andhra pradesh board $ 6th andhra pradesh boar...,lm483640,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,symmetry,AAAB
19,135964,andhra pradesh board $ 6th andhra pradesh boar...,lm483639,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of circle,AAAB
20,135965,andhra pradesh board $ 6th andhra pradesh boar...,lm483638,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of quadrilateral,AAAB
21,135966,andhra pradesh board $ 6th andhra pradesh boar...,lm483637,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,polygons,AAAB
22,135967,andhra pradesh board $ 6th andhra pradesh boar...,lm483636,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of triangle,AAAB
23,177313,engineering $ jee advanced $ mathematics $ vec...,lm205920,engineering,jee advanced,mathematics,vector algebra,3d geometry,geometrical applications,AAAF
24,177314,engineering $ jee advanced $ mathematics $ vec...,lm205918,engineering,jee advanced,mathematics,vector algebra,3d geometry,planes and geometry,AAAF
25,177315,engineering $ jee advanced $ mathematics $ vec...,lm205916,engineering,jee advanced,mathematics,vector algebra,3d geometry,straight lines,AAAF
26,177316,engineering $ jee advanced $ mathematics $ vec...,lm205913,engineering,jee advanced,mathematics,vector algebra,3d geometry,points and plane,AAAF
27,177317,engineering $ jee advanced $ mathematics $ vec...,lm205911,engineering,jee advanced,mathematics,vector algebra,3d geometry,line and plane,AAAF
28,177318,engineering $ jee advanced $ mathematics $ vec...,lm205909,engineering,jee advanced,mathematics,vector algebra,3d geometry,equation of line in different forms,AAAF
29,177319,engineering $ jee advanced $ mathematics $ vec...,lm205907,engineering,jee advanced,mathematics,vector algebra,3d geometry,plane,AAAF
30,177320,engineering $ jee advanced $ mathematics $ vec...,lm205905,engineering,jee advanced,mathematics,vector algebra,3d geometry,direction cosines and direction ratios,AAAF
31,177321,engineering $ jee advanced $ mathematics $ vec...,lm205903,engineering,jee advanced,mathematics,vector algebra,3d geometry,system of co-ordinates,AAAF
32,129093,karnataka board $ 5th karnataka state board $ ...,lm326434,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,skip counting,AAAH
33,129094,karnataka board $ 5th karnataka state board $ ...,lm326433,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,formation and comparison of numbers,AAAH
34,129095,karnataka board $ 5th karnataka state board $ ...,lm326432,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,reading and writing five digit numbers,AAAH
35,129096,karnataka board $ 5th karnataka state board $ ...,lm326431,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,place value of the digits,AAAH
36,26442,cbse $ 3rd cbse $ environmental studies $ soci...,lm21698,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,AAAC
37,27945,cbse $ 3rd cbse $ environmental studies $ soci...,lm20195,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth,AAAC
38,144452,cbse $ 3rd cbse $ environmental studies $ soci...,lm84337,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,AAAC
39,144607,cbse $ 3rd cbse $ environmental studies $ soci...,lm84030,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth,AAAC
40,148933,cbse $ 3rd cbse $ environmental studies $ soci...,lm47431,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,AAAC
41,149088,cbse $ 3rd cbse $ environmental studies $ soci...,lm47276,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth,AAAC
42,138388,jammu and kashmir board $ 3rd jammu and kashmi...,lm421442,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,design on cloth,AAAG
43,138389,jammu and kashmir board $ 3rd jammu and kashmi...,lm421441,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,cloth,AAAG
44,21172,cbse $ 4th cbse $ environmental studies $ life...,lm26968,cbse,4th cbse,environmental studies,life science,a busy month,birds,AAAD
45,21186,cbse $ 4th cbse $ environmental studies $ life...,lm26954,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest,AAAD
46,22575,cbse $ 4th cbse $ environmental studies $ life...,lm25565,cbse,4th cbse,environmental studies,life science,a busy month,animals,AAAD
47,22651,cbse $ 4th cbse $ environmental studies $ life...,lm25489,cbse,4th cbse,environmental studies,life science,a busy month,characteristics of birds,AAAD
48,144076,cbse $ 4th cbse $ environmental studies $ life...,lm85063,cbse,4th cbse,environmental studies,life science,a busy month,birds,AAAD
49,144090,cbse $ 4th cbse $ environmental studies $ life...,lm85036,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest,AAAD

In [32]:
b.to_excel('long.xlsx')

In [94]:
pwd

'C:\\Users\\Puneet Kumar\\Desktop\\Untitled Folder'

In [52]:
b[['Column4','Column5','Column6','Column7','Column8','Column10']]

,Column4,Column5,Column6,Column7,Column8,Column10
0,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",AAAA
1,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",AAAA
2,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",AAAA
3,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",AAAA
4,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",AAAA
5,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",AAAA
6,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",AAAA
7,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,AAAE
8,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,AAAE
9,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,AAAE
10,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,AAAE
11,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,AAAE
12,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,AAAE
13,lectureship,ugc net paper 2,urdu,تاریخ زبان اردو,، پراکرت و اپ بھرنش,AAAL
14,lectureship,ugc net paper 2,chinese,现代汉语语法,‘把’,AAAK
15,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1757: british colonialism and its expansion,AAAI
16,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1857: first war of independence and its conse...,AAAJ
17,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,AAAB
18,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,AAAB
19,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,AAAB
20,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,AAAB
21,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,AAAB
22,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,AAAB
23,engineering,jee advanced,mathematics,vector algebra,3d geometry,AAAF
24,engineering,jee advanced,mathematics,vector algebra,3d geometry,AAAF
25,engineering,jee advanced,mathematics,vector algebra,3d geometry,AAAF
26,engineering,jee advanced,mathematics,vector algebra,3d geometry,AAAF
27,engineering,jee advanced,mathematics,vector algebra,3d geometry,AAAF
28,engineering,jee advanced,mathematics,vector algebra,3d geometry,AAAF
29,engineering,jee advanced,mathematics,vector algebra,3d geometry,AAAF
30,engineering,jee advanced,mathematics,vector algebra,3d geometry,AAAF
31,engineering,jee advanced,mathematics,vector algebra,3d geometry,AAAF
32,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,AAAH
33,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,AAAH
34,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,AAAH
35,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,AAAH
36,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,AAAC
37,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,AAAC
38,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,AAAC
39,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,AAAC
40,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,AAAC
41,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,AAAC
42,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,AAAG
43,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,AAAG
44,cbse,4th cbse,environmental studies,life science,a busy month,AAAD
45,cbse,4th cbse,environmental studies,life science,a busy month,AAAD
46,cbse,4th cbse,environmental studies,life science,a busy month,AAAD
47,cbse,4th cbse,environmental studies,life science,a busy month,AAAD
48,cbse,4th cbse,environmental studies,life science,a busy month,AAAD
49,cbse,4th cbse,environmental studies,life science,a busy month,AAAD

In [57]:
s=b.drop_duplicates(subset=['Column10'])

In [56]:
b

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10
0,51415,10th foundation $ 10th ntse $ mathematics $ al...,lm193876,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",equations reducible to the linear form,AAAA
1,51416,10th foundation $ 10th ntse $ mathematics $ al...,lm193875,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",reducing equations to simpler form,AAAA
2,51417,10th foundation $ 10th ntse $ mathematics $ al...,lm193873,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some more applications,AAAA
3,51418,10th foundation $ 10th ntse $ mathematics $ al...,lm193871,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations having the variable on both...,AAAA
4,51419,10th foundation $ 10th ntse $ mathematics $ al...,lm193869,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",some applications,AAAA
5,51420,10th foundation $ 10th ntse $ mathematics $ al...,lm193867,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",solving equations which have linear expressio...,AAAA
6,51421,10th foundation $ 10th ntse $ mathematics $ al...,lm193865,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",introduction linear equations in one variable,AAAA
7,74553,dummy goal $ foundation 10 ntse $ scholastic a...,lm218868,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,greece,AAAE
8,74554,dummy goal $ foundation 10 ntse $ scholastic a...,lm218867,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,italy and germany,AAAE
9,74555,dummy goal $ foundation 10 ntse $ scholastic a...,lm218866,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,hungray,AAAE
10,74556,dummy goal $ foundation 10 ntse $ scholastic a...,lm218865,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,general characteristics of the movements in p...,AAAE
11,74557,dummy goal $ foundation 10 ntse $ scholastic a...,lm218864,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the ideas of gluseppe mazzini etc,AAAE
12,74558,dummy goal $ foundation 10 ntse $ scholastic a...,lm218863,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,the growth of nationalism in europe after the...,AAAE
13,95325,lectureship $ ugc net paper 2 $ urdu $ تاریخ ز...,lm522197,lectureship,ugc net paper 2,urdu,تاریخ زبان اردو,، پراکرت و اپ بھرنش,، پراکرت و اپ بھرنش,AAAL
14,93516,lectureship $ ugc net paper 2 $ chinese $ 现代汉语...,lm541533,lectureship,ugc net paper 2,chinese,现代汉语语法,‘把’,句法,AAAK
15,95589,lectureship $ ugc net paper 2 $ arab culture a...,lm402639,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1757: british colonialism and its expansion,1757: british colonialism and its expansion,AAAI
16,95588,lectureship $ ugc net paper 2 $ arab culture a...,lm402640,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1857: first war of independence and its conse...,1857: first war of independence and its conse...,AAAJ
17,135962,andhra pradesh board $ 6th andhra pradesh boar...,lm483641,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,understanding of 3d shapes,AAAB
18,135963,andhra pradesh board $ 6th andhra pradesh boar...,lm483640,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,symmetry,AAAB
19,135964,andhra pradesh board $ 6th andhra pradesh boar...,lm483639,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of circle,AAAB
20,135965,andhra pradesh board $ 6th andhra pradesh boar...,lm483638,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of quadrilateral,AAAB
21,135966,andhra pradesh board $ 6th andhra pradesh boar...,lm483637,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,polygons,AAAB
22,135967,andhra pradesh board $ 6th andhra pradesh boar...,lm483636,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,introduction of triangle,AAAB
23,177313,engineering $ jee advanced $ mathematics $ vec...,lm205920,engineering,jee advanced,mathematics,vector algebra,3d geometry,geometrical applications,AAAF
24,177314,engineering $ jee advanced $ mathematics $ vec...,lm205918,engineering,jee advanced,mathematics,vector algebra,3d geometry,planes and geometry,AAAF
25,177315,engineering $ jee advanced $ mathematics $ vec...,lm205916,engineering,jee advanced,mathematics,vector algebra,3d geometry,straight lines,AAAF
26,177316,engineering $ jee advanced $ mathematics $ vec...,lm205913,engineering,jee advanced,mathematics,vector algebra,3d geometry,points and plane,AAAF
27,177317,engineering $ jee advanced $ mathematics $ vec...,lm205911,engineering,jee advanced,mathematics,vector algebra,3d geometry,line and plane,AAAF
28,177318,engineering $ jee advanced $ mathematics $ vec...,lm205909,engineering,jee advanced,mathematics,vector algebra,3d geometry,equation of line in different forms,AAAF
29,177319,engineering $ jee advanced $ mathematics $ vec...,lm205907,engineering,jee advanced,mathematics,vector algebra,3d geometry,plane,AAAF
30,177320,engineering $ jee advanced $ mathematics $ vec...,lm205905,engineering,jee advanced,mathematics,vector algebra,3d geometry,direction cosines and direction ratios,AAAF
31,177321,engineering $ jee advanced $ mathematics $ vec...,lm205903,engineering,jee advanced,mathematics,vector algebra,3d geometry,system of co-ordinates,AAAF
32,129093,karnataka board $ 5th karnataka state board $ ...,lm326434,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,skip counting,AAAH
33,129094,karnataka board $ 5th karnataka state board $ ...,lm326433,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,formation and comparison of numbers,AAAH
34,129095,karnataka board $ 5th karnataka state board $ ...,lm326432,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,reading and writing five digit numbers,AAAH
35,129096,karnataka board $ 5th karnataka state board $ ...,lm326431,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,place value of the digits,AAAH
36,26442,cbse $ 3rd cbse $ environmental studies $ soci...,lm21698,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,AAAC
37,27945,cbse $ 3rd cbse $ environmental studies $ soci...,lm20195,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth,AAAC
38,144452,cbse $ 3rd cbse $ environmental studies $ soci...,lm84337,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,AAAC
39,144607,cbse $ 3rd cbse $ environmental studies $ soci...,lm84030,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth,AAAC
40,148933,cbse $ 3rd cbse $ environmental studies $ soci...,lm47431,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,AAAC
41,149088,cbse $ 3rd cbse $ environmental studies $ soci...,lm47276,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,cloth,AAAC
42,138388,jammu and kashmir board $ 3rd jammu and kashmi...,lm421442,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,design on cloth,AAAG
43,138389,jammu and kashmir board $ 3rd jammu and kashmi...,lm421441,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,cloth,AAAG
44,21172,cbse $ 4th cbse $ environmental studies $ life...,lm26968,cbse,4th cbse,environmental studies,life science,a busy month,birds,AAAD
45,21186,cbse $ 4th cbse $ environmental studies $ life...,lm26954,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest,AAAD
46,22575,cbse $ 4th cbse $ environmental studies $ life...,lm25565,cbse,4th cbse,environmental studies,life science,a busy month,animals,AAAD
47,22651,cbse $ 4th cbse $ environmental studies $ life...,lm25489,cbse,4th cbse,environmental studies,life science,a busy month,characteristics of birds,AAAD
48,144076,cbse $ 4th cbse $ environmental studies $ life...,lm85063,cbse,4th cbse,environmental studies,life science,a busy month,birds,AAAD
49,144090,cbse $ 4th cbse $ environmental studies $ life...,lm85036,cbse,4th cbse,environmental studies,life science,a busy month,bird's nest,AAAD

In [58]:
s

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10
0,51415,10th foundation $ 10th ntse $ mathematics $ al...,lm193876,10th foundation,10th ntse,mathematics,algebra,"""linear equations in one variable",equations reducible to the linear form,AAAA
7,74553,dummy goal $ foundation 10 ntse $ scholastic a...,lm218868,dummy goal,foundation 10 ntse,scholastic aptitude test,history,"""the rise of nationalism in europe """,greece,AAAE
13,95325,lectureship $ ugc net paper 2 $ urdu $ تاریخ ز...,lm522197,lectureship,ugc net paper 2,urdu,تاریخ زبان اردو,، پراکرت و اپ بھرنش,، پراکرت و اپ بھرنش,AAAL
14,93516,lectureship $ ugc net paper 2 $ chinese $ 现代汉语...,lm541533,lectureship,ugc net paper 2,chinese,现代汉语语法,‘把’,句法,AAAK
15,95589,lectureship $ ugc net paper 2 $ arab culture a...,lm402639,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1757: british colonialism and its expansion,1757: british colonialism and its expansion,AAAI
16,95588,lectureship $ ugc net paper 2 $ arab culture a...,lm402640,lectureship,ugc net paper 2,arab culture and islamic studies,islam in india,1857: first war of independence and its conse...,1857: first war of independence and its conse...,AAAJ
17,135962,andhra pradesh board $ 6th andhra pradesh boar...,lm483641,andhra pradesh board,6th andhra pradesh board,mathematics,geometry,2d - 3d shapes,understanding of 3d shapes,AAAB
23,177313,engineering $ jee advanced $ mathematics $ vec...,lm205920,engineering,jee advanced,mathematics,vector algebra,3d geometry,geometrical applications,AAAF
32,129093,karnataka board $ 5th karnataka state board $ ...,lm326434,karnataka board,5th karnataka state board,mathematics,arithmetic,5 - digit numbers,skip counting,AAAH
36,26442,cbse $ 3rd cbse $ environmental studies $ soci...,lm21698,cbse,3rd cbse,environmental studies,social science,a beautiful cloth,design on cloth,AAAC
42,138388,jammu and kashmir board $ 3rd jammu and kashmi...,lm421442,jammu and kashmir board,3rd jammu and kashmir board,environmental studies,social science,a beautiful cloth,design on cloth,AAAG
44,21172,cbse $ 4th cbse $ environmental studies $ life...,lm26968,cbse,4th cbse,environmental studies,life science,a busy month,birds,AAAD

In [59]:
s.to_excel('short.xlsx')